<?php
/**
 * @file
 * Code for the agency_location feature.
 */

include_once 'agency_location.features.inc';

/**
 * Implements hook_leaflet_views_alter_points_data_alter().
 */
function agency_location_leaflet_views_alter_points_data_alter($result,&$points) {
  if (isset($result->nid)) {
    $points[0]['entity'] = node_load($result->nid);
  }
}

/**
 * Implements hook_leaflet_views_alter_points_data_alter().
 */
function agency_location_leaflet_map_prebuild_alter(&$settings) {
  foreach ($settings['features'] as &$feature) {
    if (isset($feature['icon']['iconUrl']) && is_numeric($feature['icon']['iconUrl'])) {
      $node = node_load($feature['icon']['iconUrl']);
      $marker_suffix = empty($node->field_unit) ? '' : 'to';
      $feature['icon']['iconUrl'] = 'sites/all/modules/features/agency_location/images/marker' . $marker_suffix . '.png';
    }
  }

}
