<?php
/**
 * @file
 * Code for the agency_units feature.
 */

include_once 'agency_units.features.inc';

/**
 * Implements hook_views_default_views_alter().
 */
function agency_units_views_default_views_alter(&$views) {
  if (array_key_exists('bookable_units', $views)) {
    $view = $views['bookable_units'];
    $handler =& $view->display['default']->handler;
    $handler->display->display_options['access']['type'] = 'role';
    $handler->display->display_options['access']['role'] = array(
      3 => '3',
      4 => '4',
    );
  }
}

/**
 * Implements hook_views_pre_build()
 *
 * Allow agency owners to see all units on the 'My bookable units' view.
 */
function agency_units_views_pre_build(&$view) {

  // Using this permission as a proxy for admin or agency manager roles.
  // @todo: agency-specific permission needed?
  if ($view->name == 'my_bookable_units' && user_access('update any rooms_unit entity')) {
    unset($view->argument['uid']);
  }
}

/**
 * Implements hook_form_FORMID_alter()
 *
 * Modifications to availability search form on unit pages.
 */
function agency_units_form_rooms_booking_availability_search_form_block_alter(&$form, $form_state) {
  if ($unit = menu_get_object('rooms_unit', 1)) {
    $params = drupal_get_query_parameters();

    $form['bookable_units']['#default_value'] = $unit->unit_id;
    $form['bookable_units']['#access'] = FALSE;

    if (isset($params['rooms_start_date']['date']) && !empty($params['rooms_start_date']['date'])) {
      $arrivalDateTime = DateTime::createFromFormat('d/m/Y', $params['rooms_start_date']['date']);
      $arrival = $arrivalDateTime->format('Y-m-d');
      $form['rooms_date_range']['rooms_start_date']['#default_value'] = $arrival;
    }
    if (isset($params['rooms_end_date']['date']) && !empty($params['rooms_end_date']['date'])) {
      $endDateTime = DateTime::createFromFormat('d/m/Y', $params['rooms_end_date']['date']);
      $end = $endDateTime->format('Y-m-d');
      $form['rooms_date_range']['rooms_end_date']['#default_value'] = $end;
    }
    if (isset($params['group_size'])) {
      $form['rooms_fieldset']['group_size_adults:1']['#default_value'] = $params['group_size'];
    }

    if (isset($params['rooms_start_date']['date']) && isset($params['rooms_end_date']['date']) && isset($params['group_size'])) {
      $form['actions']['submit']['#value'] = t('Book Now');
    }
  }
}

/**
 * Implements hook_form_FORMID_alter()
 *
 * Modifications to unit creation form for property owners.
 */
function agency_units_form_rooms_unit_edit_form_alter(&$form, $form_state) {

  // Set property owner field to author if no value is present.
  if (empty($form['field_owner'][LANGUAGE_NONE][0]['target_id']['#default_value'])) {
    $author = user_load($form['#entity']->uid);
    $form['field_owner'][LANGUAGE_NONE][0]['target_id']['#default_value'] = $author->name . ' (' . $author->uid . ')';
  }

  // Unit creation modifications.
  if (!empty($form['#entity']->is_new)) {

    // Using this permission as a proxy for admin or agency manager roles.
    // @todo: agency-specific permission needed?
    if (!user_access('update any rooms_unit entity')) {

      // Don't let property owners publish their own units.
      $form['options']['status']['#default_value'] = FALSE;

      // Add our submission handler.
      $form['actions']['submit']['#submit'][] = 'agency_units_rooms_unit_edit_submit';
    }
  }
}

/**
 * Submit handler for rooms unit creation - This only runs for property owners.
 */
function agency_units_rooms_unit_edit_submit($form, &$form_state) {

  // Redirect to the my units page.
  $form_state['redirect'] = 'admin/rooms/my-units';
}
