<?php
/**
 * @file
 * agency_units.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function agency_units_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'rooms_unit-bnb-field_address'
  $field_instances['rooms_unit-bnb-field_address'] = array(
    'bundle' => 'bnb',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'addressfield',
        'settings' => array(
          'format_handlers' => array(
            0 => 'address',
          ),
          'use_widget_handlers' => 1,
        ),
        'type' => 'addressfield_default',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'rooms_unit',
    'field_name' => 'field_address',
    'label' => 'Address',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'addressfield',
      'settings' => array(
        'available_countries' => array(),
        'default_country' => '',
        'format_handlers' => array(
          'address' => 'address',
          'address-hide-country' => 0,
          'organisation' => 0,
          'name-full' => 0,
          'name-oneline' => 0,
        ),
      ),
      'type' => 'addressfield_standard',
      'weight' => 10,
    ),
  );

  // Exported field_instance: 'rooms_unit-bnb-field_area'
  $field_instances['rooms_unit-bnb-field_area'] = array(
    'bundle' => 'bnb',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'rooms_unit',
    'field_name' => 'field_area',
    'label' => 'Area',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'taxonomy',
      'settings' => array(
        'autocomplete_path' => 'taxonomy/autocomplete',
        'size' => 60,
      ),
      'type' => 'taxonomy_autocomplete',
      'weight' => 8,
    ),
  );

  // Exported field_instance: 'rooms_unit-bnb-field_availability_calendar'
  $field_instances['rooms_unit-bnb-field_availability_calendar'] = array(
    'bundle' => 'bnb',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'rooms_availability_reference',
        'settings' => array(),
        'type' => 'rooms_availability_reference_default',
        'weight' => 5,
      ),
    ),
    'entity_type' => 'rooms_unit',
    'field_name' => 'field_availability_calendar',
    'label' => 'Availability Calendar',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'rooms_availability_reference',
      'settings' => array(
        'autocomplete_match' => 'contains',
        'autocomplete_path' => 'rooms_availability_reference/autocomplete',
        'size' => 60,
      ),
      'type' => 'rooms_availability_reference_autocomplete',
      'weight' => 13,
    ),
  );

  // Exported field_instance: 'rooms_unit-bnb-field_location'
  $field_instances['rooms_unit-bnb-field_location'] = array(
    'bundle' => 'bnb',
    'default_value' => array(),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 11,
      ),
    ),
    'entity_type' => 'rooms_unit',
    'field_name' => 'field_location',
    'label' => 'Location',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'geofield_gmap',
      'settings' => array(
        'click_to_place_marker' => FALSE,
        'confirm_center_marker' => FALSE,
        'html5_geolocation' => 0,
        'map_type' => 'ROADMAP',
      ),
      'type' => 'geofield_gmap',
      'weight' => 9,
    ),
  );

  // Exported field_instance: 'rooms_unit-bnb-field_owner'
  $field_instances['rooms_unit-bnb-field_owner'] = array(
    'bundle' => 'bnb',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter the user name of this property\'s owner, whose contact information will be shown on unit pages. This field defaults to this unit\'s author, but may be set to another user.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'link' => FALSE,
        ),
        'type' => 'entityreference_label',
        'weight' => 12,
      ),
    ),
    'entity_type' => 'rooms_unit',
    'field_name' => 'field_owner',
    'label' => 'Owner',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'entityreference',
      'settings' => array(
        'match_operator' => 'CONTAINS',
        'path' => '',
        'size' => 60,
      ),
      'type' => 'entityreference_autocomplete',
      'weight' => 14,
    ),
  );

  // Exported field_instance: 'rooms_unit-bnb-field_property_description'
  $field_instances['rooms_unit-bnb-field_property_description'] = array(
    'bundle' => 'bnb',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 8,
      ),
    ),
    'entity_type' => 'rooms_unit',
    'field_name' => 'field_property_description',
    'label' => 'Property Description',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 11,
    ),
  );

  // Exported field_instance: 'rooms_unit-bnb-field_property_featured'
  $field_instances['rooms_unit-bnb-field_property_featured'] = array(
    'bundle' => 'bnb',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => 'Check this box if this property is featured.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 10,
      ),
    ),
    'entity_type' => 'rooms_unit',
    'field_name' => 'field_property_featured',
    'label' => 'Property Featured',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'rooms_unit-bnb-field_property_gallery'
  $field_instances['rooms_unit-bnb-field_property_gallery'] = array(
    'bundle' => 'bnb',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'nivo_formatter',
        'settings' => array(
          'nivo_formatter_image_style' => 'large',
          'nivo_formatter_nivo_slider' => array(
            'animSpeed' => 500,
            'boxCols' => 8,
            'boxRows' => 4,
            'captionOpacity' => 0.8,
            'controlNav' => TRUE,
            'directionNav' => 1,
            'directionNavHide' => TRUE,
            'effect' => array(
              'random' => 'random',
            ),
            'keyboardNav' => TRUE,
            'manualAdvance' => 0,
            'nextText' => 'Next',
            'pauseOnHover' => TRUE,
            'pauseTime' => 3000,
            'prevText' => 'Prev',
            'slices' => 15,
            'startSlide' => 0,
          ),
          'nivo_formatter_theme' => 'default',
          'nivo_slider_thumbnail' => array(
            'controlNavThumbs' => TRUE,
            'thumbnail_style' => 'thumbnail',
          ),
        ),
        'type' => 'nivo_formatter',
        'weight' => 7,
      ),
    ),
    'entity_type' => 'rooms_unit',
    'field_name' => 'field_property_gallery',
    'label' => 'Property Gallery',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'filefield_sources' => array(
          'filefield_sources' => array(
            'attach' => 0,
            'clipboard' => 0,
            'plupload' => 'plupload',
            'reference' => 0,
            'remote' => 0,
            'upload' => 0,
          ),
          'source_attach' => array(
            'absolute' => 0,
            'attach_mode' => 'move',
            'path' => 'file_attach',
          ),
          'source_imce' => array(
            'imce_mode' => 0,
          ),
          'source_reference' => array(
            'autocomplete' => 0,
          ),
        ),
        'manualcrop_crop_info' => 1,
        'manualcrop_default_crop_area' => 1,
        'manualcrop_enable' => 1,
        'manualcrop_inline_crop' => 0,
        'manualcrop_instant_crop' => 0,
        'manualcrop_instant_preview' => 1,
        'manualcrop_require_cropping' => array(
          'homepage_features' => 0,
          'property_slider' => 'property_slider',
        ),
        'manualcrop_styles_list' => array(
          'homepage_features' => 0,
          'property_slider' => 'property_slider',
        ),
        'manualcrop_styles_mode' => 'include',
        'manualcrop_thumblist' => 1,
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'rooms_unit-bnb-field_property_image'
  $field_instances['rooms_unit-bnb-field_property_image'] = array(
    'bundle' => 'bnb',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 6,
      ),
    ),
    'entity_type' => 'rooms_unit',
    'field_name' => 'field_property_image',
    'label' => 'Property Image',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'filefield_sources' => array(
          'filefield_sources' => array(
            'attach' => 0,
            'clipboard' => 0,
            'plupload' => 0,
            'reference' => 0,
            'remote' => 0,
            'upload' => 'upload',
          ),
          'source_attach' => array(
            'absolute' => 0,
            'attach_mode' => 'move',
            'path' => 'file_attach',
          ),
          'source_imce' => array(
            'imce_mode' => 0,
          ),
          'source_reference' => array(
            'autocomplete' => 0,
          ),
        ),
        'manualcrop_crop_info' => 1,
        'manualcrop_default_crop_area' => 1,
        'manualcrop_enable' => 1,
        'manualcrop_inline_crop' => 0,
        'manualcrop_instant_crop' => 0,
        'manualcrop_instant_preview' => 1,
        'manualcrop_require_cropping' => array(
          'homepage_features' => 'homepage_features',
          'property_slider' => 0,
        ),
        'manualcrop_styles_list' => array(
          'homepage_features' => 'homepage_features',
          'property_slider' => 0,
        ),
        'manualcrop_styles_mode' => 'include',
        'manualcrop_thumblist' => 1,
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'rooms_unit-bnb-og_unit_location_ref'
  $field_instances['rooms_unit-bnb-og_unit_location_ref'] = array(
    'bundle' => 'bnb',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'link' => FALSE,
        ),
        'type' => 'entityreference_label',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'rooms_unit',
    'field_name' => 'og_unit_location_ref',
    'label' => 'Groups audience',
    'required' => FALSE,
    'settings' => array(
      'behaviors' => array(
        'og_widget' => array(
          'admin' => array(
            'widget_type' => 'entityreference_autocomplete',
          ),
          'default' => array(
            'widget_type' => 'options_select',
          ),
          'status' => TRUE,
        ),
      ),
      'user_register_form' => FALSE,
    ),
    'view modes' => array(
      'full' => array(
        'custom settings' => FALSE,
        'label' => 'Full',
        'type' => 'og_list_default',
      ),
      'teaser' => array(
        'custom settings' => FALSE,
        'label' => 'Teaser',
        'type' => 'og_list_default',
      ),
    ),
    'widget' => array(
      'module' => 'entityreference',
      'settings' => array(
        'match_operator' => 'CONTAINS',
        'path' => '',
        'size' => 60,
      ),
      'type' => 'entityreference_autocomplete',
      'weight' => 12,
    ),
  );

  // Exported field_instance: 'rooms_unit-bnb-rooms_booking_unit_options'
  $field_instances['rooms_unit-bnb-rooms_booking_unit_options'] = array(
    'bundle' => 'bnb',
    'default_value' => array(),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'rooms',
        'settings' => array(),
        'type' => 'rooms_options_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'rooms_unit',
    'field_name' => 'rooms_booking_unit_options',
    'label' => 'Options',
    'required' => FALSE,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'rooms',
      'settings' => array(),
      'type' => 'rooms_options_combined',
      'weight' => 11,
    ),
  );

  // Exported field_instance:
  // 'rooms_unit_type-rooms_unit_type-rooms_booking_unit_options'
  $field_instances['rooms_unit_type-rooms_unit_type-rooms_booking_unit_options'] = array(
    'bundle' => 'rooms_unit_type',
    'default_value' => array(),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'rooms',
        'settings' => array(),
        'type' => 'rooms_options_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'rooms_unit_type',
    'field_name' => 'rooms_booking_unit_options',
    'label' => 'Options',
    'required' => FALSE,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'rooms',
      'settings' => array(),
      'type' => 'rooms_options_combined',
      'weight' => 0,
    ),
  );

  // Exported field_instance: 'taxonomy_term-location-field_location_featured'
  $field_instances['taxonomy_term-location-field_location_featured'] = array(
    'bundle' => 'location',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_location_featured',
    'label' => 'Location Featured',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'taxonomy_term-location-field_location_image'
  $field_instances['taxonomy_term-location-field_location_image'] = array(
    'bundle' => 'location',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_location_image',
    'label' => 'Location Image',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'filefield_sources' => array(
          'filefield_sources' => array(),
          'source_attach' => array(
            'absolute' => 0,
            'attach_mode' => 'move',
            'path' => 'file_attach',
          ),
          'source_imce' => array(
            'imce_mode' => 0,
          ),
          'source_reference' => array(
            'autocomplete' => 0,
          ),
        ),
        'manualcrop_crop_info' => 1,
        'manualcrop_default_crop_area' => 1,
        'manualcrop_enable' => 1,
        'manualcrop_inline_crop' => 0,
        'manualcrop_instant_crop' => 1,
        'manualcrop_instant_preview' => 1,
        'manualcrop_require_cropping' => array(
          'homepage_features' => 'homepage_features',
        ),
        'manualcrop_styles_list' => array(
          'homepage_features' => 0,
        ),
        'manualcrop_styles_mode' => 'exclude',
        'manualcrop_thumblist' => 1,
        'preview_image_style' => 'thumbnail',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 2,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Address');
  t('Area');
  t('Availability Calendar');
  t('Check this box if this property is featured.');
  t('Enter the user name of this property\'s owner, whose contact information will be shown on unit pages. This field defaults to this unit\'s author, but may be set to another user.');
  t('Groups audience');
  t('Location');
  t('Location Featured');
  t('Location Image');
  t('Options');
  t('Owner');
  t('Property Description');
  t('Property Featured');
  t('Property Gallery');
  t('Property Image');

  return $field_instances;
}
