<?php
/**
 * @file
 * Code for the agency_system feature.
 */

include_once 'agency_system.features.inc';

/**
 * @file
 * Hooks and API functions for agency_system module.
 */

/**
 * Implements hook_menu_link_alter()
 *
 * Allow altering the base commerce admin menu items.
 */
function agency_system_menu_link_alter(&$item) {
  if ($item['path'] == 'admin/commerce' || $item['path'] == 'admin/commerce/config') {
    $item['options']['alter'] = TRUE;
  }
}

/**
 * Implements hook_translated_menu_link_alter()
 *
 * Alter the base commerce admin menu items to not allow property owners to
 * see them. (Using the "Configure Rooms" permission as a proxy)
 */
function agency_system_translated_menu_link_alter(&$item, $map) {
  if ($item['link_path'] == 'admin/commerce' || $item['link_path'] == 'admin/commerce/config') {
    if (!user_access('configure room settings')) {
      $item['access'] = FALSE;
    }
  }
}

/**
 * Implements hook_rooms_booking_availabilityagent_filter().
 */
function agency_system_rooms_booking_availabilityagent_filter() {
  return array(
    'availability_agent_unit_filter' => array(
      'label' => t('Units'),
      'handler' => array(
        'class' => 'AvailabilityAgentUnitFilter',
      ),
    ),
  );
}

function agency_system_field_access($op, $field, $entity_type, $entity, $account) {
  // Restrict access for Field location featured.
  if ($entity_type == 'taxonomy_term') {
    if ($field['field_name'] == 'field_location_featured') {
      // Only administrator and agency_owner can edit this field.
      if (!(isset($account->roles[3]) || isset($account->roles[4]))) {
        if ($op == 'edit') {
          return false;
        }
      }
    }
  }
  // Restrict access for Field property featured.
  if ($entity_type == 'rooms_unit') {
    if ($field['field_name'] == 'field_property_featured') {
      // Only administrator and Agency owner can edit this field.
      if (!(isset($account->roles[3]) || isset($account->roles[4]))) {
        if ($op == 'edit') {
          return false;
        }
      }
    }
  }
}
